version: '3.8'
services:
    mysql-db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: autos10a
            MYSQL_USER: autos
            MYSQL_PASSWORD: passwordautos
        volumes:
            - ./mysql.data:/var/lib/mysql
    app:
        build:
            context: ./gpds-autos
            dockerfile: Dockerfile
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/autos10a
            SPRING_DATASOURCE_USERNAME: autos
            SPRING_DATASOURCE_PASSWORD: passwordautos
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
        ports:
            - "8082:8080"
        depends_on:
            - mysql-db
